//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hra.Intra.sigh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        public int IdPaciente { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string TercerNombre { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string NroDocumento { get; set; }
        public string Telefono { get; set; }
        public string DireccionDomicilio { get; set; }
        public string Autogenerado { get; set; }
        public Nullable<int> IdTipoSexo { get; set; }
        public Nullable<int> IdProcedencia { get; set; }
        public Nullable<int> IdGradoInstruccion { get; set; }
        public Nullable<int> IdEstadoCivil { get; set; }
        public Nullable<int> IdDocIdentidad { get; set; }
        public Nullable<int> IdTipoOcupacion { get; set; }
        public Nullable<int> IdCentroPobladoNacimiento { get; set; }
        public Nullable<int> IdCentroPobladoDomicilio { get; set; }
        public string NombrePadre { get; set; }
        public string NombreMadre { get; set; }
        public Nullable<int> NroHistoriaClinica { get; set; }
        public Nullable<int> IdTipoNumeracion { get; set; }
        public Nullable<int> IdCentroPobladoProcedencia { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdPaisDomicilio { get; set; }
        public Nullable<int> IdPaisProcedencia { get; set; }
        public Nullable<int> IdPaisNacimiento { get; set; }
        public Nullable<int> IdDistritoProcedencia { get; set; }
        public Nullable<int> IdDistritoDomicilio { get; set; }
        public Nullable<int> IdDistritoNacimiento { get; set; }
        public string FichaFamiliar { get; set; }
        public string IdEtnia { get; set; }
        public string GrupoSanguineo { get; set; }
        public string FactorRh { get; set; }
        public Nullable<bool> UsoWebReniec { get; set; }
        public Nullable<int> idIdioma { get; set; }
        public string Email { get; set; }
        public string madreDocumento { get; set; }
        public string madreApellidoPaterno { get; set; }
        public string madreApellidoMaterno { get; set; }
        public string madrePrimerNombre { get; set; }
        public string madreSegundoNombre { get; set; }
        public Nullable<int> NroOrdenHijo { get; set; }
        public Nullable<int> madreTipoDocumento { get; set; }
        public string Sector { get; set; }
        public Nullable<int> Sectorista { get; set; }
    }
}
